# Copyright (c) 2018, WSO2 Inc. (http://wso2.com) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
jdk:
  - openjdk8

before_install:
  - sudo apt-get update
  - sudo apt-get install libaio-dev

script:

  - BALLERINA_VERSION="${VERSION:-0.991.1-SNAPSHOT}"
  - echo -e "\033[36m${BALLERINA_VERSION}\033[m"

  - DISTRIBUTION_NAME=ballerina-${BALLERINA_VERSION}
  - echo -e "\033[36m${DISTRIBUTION_NAME}\033[m"

  - DOWNLOAD_CHANNEL=${CHANNEL:-nightly}
  - echo -e "\033[36m${DOWNLOAD_CHANNEL}\033[m"

  - DOWNLOAD_LOCATION="${URL:-https://product-dist.ballerina.io}"
  - echo -e "\033[36m${DOWNLOAD_LOCATION}\033[m"

  - echo -e "\033[36m${DOWNLOAD_LOCATION}/${DOWNLOAD_CHANNEL}/${BALLERINA_VERSION}/${DISTRIBUTION_NAME}.zip\033[m"
  - wget ${DOWNLOAD_LOCATION}/${DOWNLOAD_CHANNEL}/${BALLERINA_VERSION}/${DISTRIBUTION_NAME}.zip

  - unzip -q ${DISTRIBUTION_NAME}.zip

  - export PATH=${PATH}:$(pwd)/${DISTRIBUTION_NAME}/bin

  - ballerina version

  - ACTIVEMQ_VERSION=5.12.0
  - ACTIVEMQ_DISTRIBUTION_NAME=apache-activemq-${ACTIVEMQ_VERSION}

  - echo -e "\033[36mhttps://archive.apache.org/dist/activemq/${ACTIVEMQ_VERSION}/${ACTIVEMQ_DISTRIBUTION_NAME}-bin.tar.gz\033[m"
  - wget https://archive.apache.org/dist/activemq/${ACTIVEMQ_VERSION}/${ACTIVEMQ_DISTRIBUTION_NAME}-bin.tar.gz

  - tar xzf ${ACTIVEMQ_DISTRIBUTION_NAME}-bin.tar.gz

  - ARTEMIS_VERSION=2.9.0
  - ARTEMIS_DISTRIBUTION_NAME=apache-artemis-${ARTEMIS_VERSION}
  - ARTEMIS_HOME=/var/lib

  - echo -e "\033[36mhttps://archive.apache.org/dist/activemq/activemq-artemis/${ARTEMIS_VERSION}/${ARTEMIS_DISTRIBUTION_NAME}-bin.tar.gz\033[m"
  - wget https://archive.apache.org/dist/activemq/activemq-artemis/${ARTEMIS_VERSION}/${ARTEMIS_DISTRIBUTION_NAME}-bin.tar.gz

  - tar xzf ${ARTEMIS_DISTRIBUTION_NAME}-bin.tar.gz
  - ./${ARTEMIS_DISTRIBUTION_NAME}/bin/artemis create /tmp/mybroker --user admin --password admin123 --allow-anonymous Y


  - ./${ACTIVEMQ_DISTRIBUTION_NAME}/bin/activemq start
  - /home/travis/build/paramids/IpFour/Y/bin/artemis-service start

  - cp ${ACTIVEMQ_DISTRIBUTION_NAME}/lib/activemq-client-5.12.0.jar ${DISTRIBUTION_NAME}/bre/lib
  - cp ${ACTIVEMQ_DISTRIBUTION_NAME}/lib/geronimo-j2ee-management_1.1_spec-1.0.1.jar ${DISTRIBUTION_NAME}/bre/lib
  - cp ${ACTIVEMQ_DISTRIBUTION_NAME}/lib/hawtbuf-1.11.jar ${DISTRIBUTION_NAME}/bre/lib

  - cp ${ARTEMIS_DISTRIBUTION_NAME}/lib/*.jar ${DISTRIBUTION_NAME}/bre/lib

  - cd src

  - ballerina init

  - ballerina test
